on:
  push:
    branches: main
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: running a custom script
        run: |
          ls -al
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: check java version
        run: java -version
      #- name: gradle build
      #  run: gradle build
      - name: docker version
        run: |
          docker -v
          docker
          docker images -a
      - name: docker compose
        run: docker-compose up -d
      
